apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-validat-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-validat-role
rules:
  - verbs: ["*"]
    resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
    apiGroups: ["admissionregistration.k8s.io"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admission-validat-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission-validat-role
subjects:
  - kind: ServiceAccount
    name: admission-validat-sa
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-validat
  labels:
    app: admission-validat
spec:
  selector:
    matchLabels:
      app: admission-validat
  template:
    metadata:
      labels:
        app: admission-validat
    spec:
      serviceAccountName: admission-validat-sa
      initContainers:
        - image: langhub/admission-validat-tls:v0.0.2
          imagePullPolicy: IfNotPresent
          name: webhook-init
          env:
            - name: WEBHOOK_NAMESPACE
              value: default
            - name: MUTATE_CONFIG
              value: admission-validat-mutate
            - name: VALIDATE_CONFIG
              value: admission-validat
            - name: WEBHOOK_SERVICE
              value: admission-validat
            - name: VALIDATE_PATH
              value: /validate
            - name: MUTATE_PATH
              value: /mutate
          volumeMounts:
            - mountPath: /etc/webhook/certs
              name: webhook-certs
      containers:
        - name: webhook
          image: langhub/admission-validat:v0.1.6
          imagePullPolicy: IfNotPresent
          env:
            - name: WHITELIST_REGISTRIES
              value: "docker.io,gcr.io"
          ports:
            - containerPort: 443
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: admission-validat
  labels:
    app: admission-validat
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: admission-validat